### ISSUE TITLE
Do not continue on download error (install_bigfix)

### ISSUE THREAD

**Issue by strawgate** [jgstew/tools#10]
Script currently continues even if the installer fails to download or impartially downloads (it doesnt verify the download either).

Script also seems to continue if the masthead download failed

**Comment by jgstew** [comment]
**Affected Files:**
- https://github.com/jgstew/tools/blob/master/bash/install_bigfix.sh
- https://github.com/jgstew/tools/blob/master/CMD/install_bigfix.bat

**Related:** https://github.com/jgstew/tools/issues/7

**Comment by jgstew** [comment]
How would I "verify" the download?

**Comment by strawgate** [comment]
I think failing on download error is probably sufficient -- they publish SHA256 here: http://support.bigfix.com/bes/release/9.5/patch2/SHA256SUMS which could be used to verify the download.

**Comment by jgstew** [comment]
part of the problem with verifying the SHA256 before install is that is yet another download, where every download is potentially problematic.

**Comment by jgstew** [comment]
I do have the file downloads in this script put into a function call, which is much better: https://github.com/jgstew/tools/blob/master/bash/bigfix_newest_version.sh

I'll need to do something like this to put in better handling of downloads.

**Comment by jgstew** [comment]
This script will help me handle the downloads more gracefully and generically: https://github.com/jgstew/tools/blob/master/bash/download_file.sh

**Comment by jgstew** [comment]
added some error checking so that the script will stop if one of the downloads failed: https://github.com/jgstew/tools/commit/ecf3c60e86822f0de8bca523084bb1d121b4dad6
