### ISSUE TITLE
Support offline firewalld (install_bigfix)

### ISSUE THREAD

**Issue by atlauren** [jgstew/tools#13]
#### Affected Files:
- https://github.com/jgstew/tools/blob/master/bash/install_bigfix.sh

When inside a linux kickstart (e.g. anaconda), firewalld is likely not running.  Also, if the system supports firewalld, there is little gain in writing a ipchain.  This suggested change detects if firewalld is not running, and in that case uses firewall-offline-cmd.  If it is running, it also reloads firewalld.  And, an if loop only runs iptables if the system doesn't have firewall-cmd.

```
# open up linux firewall to accept UDP 52311
if command_exists firewall-cmd ; then
	# open up linux firewall to accept UDP 52311 - firewall-cmd
	#test if running
	FW_STATUS=`/bin/firewall-cmd --state`
	if [[ $FW_STATUS = "running" ]] ; then
		/bin/firewall-cmd --permanent --add-port=52311/udp
		/bin/firewall-cmd --reload
		else
		#not running
		/bin/firewall-offline-cmd --add-port=52311/udp
	fi
elif command_exists firewall-offline-cmd ; then
	# maybe we're in anaconda
		/bin/firewall-offline-cmd --add-port=52311/udp
else
	# open up linux firewall to accept UDP 52311 - iptables
		iptables -A INPUT -p udp --dport 52311 -j ACCEPT
fi
```

**Comment by jgstew** [comment]
This is anaconda? https://en.wikipedia.org/wiki/Anaconda_(installer)

I don't fully understand the difference between the effects of `iptables` vs the newer `firewall-cmd` in these OSes. I figure if both are present, then I should add a rule to both, even if not needed incase for some reason `iptables` takes effect. 

So `firewall-offline-cmd` is for adding firewall rules during the install phase? Does this command exist when outside of `anaconda`?

In general, I'd prefer just calling the command if it exists without doing any checking as long as it doesn't cause a problem.

Also, I'd rather not hardcode paths like `/bin/firewall-cmd` if it is in the PATH since it isn't required and could cause breakage between different OSes.

**Comment by jgstew** [comment]
Assuming this doesn't cause any issues, this is what I would do instead:

```
if command_exists firewall-cmd ; then
  firewall-cmd --permanent --add-port=52311/udp
fi
if command_exists firewall-offline-cmd ; then
  firewall-offline-cmd --add-port=52311/udp
fi
if command_exists firewall-cmd ; then
  iptables -A INPUT -p udp --dport 52311 -j ACCEPT
fi
```

**Comment by atlauren** [comment]
firewalld is the new thing, iptables is the old thing.  If firewalld is there, it's best to do it there.  I generally prefer to determine the proper thing to do, and do only that.  I dislike splatting changes into all the possibilities.

And yes, that is anaconda. It is a limited environment; some things are there, some things aren't. Binary locations are most often (always?) the same as the full OS, but the standard path often isn't (depends on the OS version). I've learned to not rely on paths environments, but instead use direct paths to binaries.

**Comment by jgstew** [comment]
"I generally prefer to determine the proper thing to do, and do only that. I dislike splatting changes into all the possibilities."

I completely agree, but not in this case. If `iptables` is present and can have a rule be added to it, and could be activated at some point in the future, then the rule should go there in addition to in `firewalld`. If `iptables` isn't being used, then adding a rule to it will have no effect. It is not worth the added complexity of the code to avoid adding a rule to `iptables` that may actually be required in some rare cases.

The point of this script is to maximize success in getting a configuration management system installed.

I would also prefer to not hard code the direct paths to the binaries unless the script is shown to fail and this is required to address the issue. This adds complexity and makes it harder to address dependancies by bundling them with the script.

**Comment by jgstew** [comment]
I added support for `firewall-offline-cmd` in this commit: https://github.com/jgstew/tools/commit/c416f7ad64908911fd39b5d4c20ac2a578b8fc41

**Comment by atlauren** [comment]
I'll take it.  👍
My internal version might be different though. 😉

**Comment by jgstew** [comment]
maintaining a slightly different set of code might be worth the effort, but it doesn't sound like fun.

You really should fork this on github so you can do it publicly.

**Comment by jgstew** [comment]
I'd be interested to know if my code works as is in anaconda if you ever test it.
