### ISSUE TITLE
Trying to implement automatic patching on windows platform

### ISSUE THREAD

**Issue by akashsarpate** [jgstew/tools#21]
I following one of your blog for automating patching on windows.
https://bigfix.me/fixlet/details/6132
we have monthly windows updates which are currently applying manually by using bigfix client on windows server.
We want to make script which will automatically install these windows updates from bigfix client.
I followed your blog and it is possible using REST API.
i am trying to run baseline file (.bes) whihc you shared on https://bigfix.me/fixlet/details/6132 
PS C:\Program Files (x86)\BigFix Enterprise\BES Server API> . .\BESImportFile-1.3.exe  servername  username password "Windows_update.bes"
BESAPI.XMLImporter.ImportFile error: HTTP Error 28: Timeout was reached: Connection timed out after 10000 milliseconds

Any idea how i can proceed?

**Comment by jgstew** [comment]
that timeout suggests that the URL is wrong or similar. That means it isn't reaching the root at all.

**Comment by jgstew** [comment]
This question would be best answered over at forum.bigfix.com
